sudo: required
before_install:
  - curl -O https://raw.githubusercontent.com/scottkosty/install-tl-ubuntu/master/install-tl-ubuntu
  - chmod +x ./install-tl-ubuntu
install:
  - sudo ./install-tl-ubuntu --profile="$(pwd)/texlive.profile"
  - export PATH=$(cat /etc/environment):$PATH
  - tlmgr install classicthesis
  - tlmgr install koma-script
script:
  - make tex
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - make upload
  - make invalidate
notifications:
  email: false
  slack:
    secure: IhGd0NkKkldDt6xwvNi4wK37fTN/0RMPy89bSYUsaLVazNRi29KfkmWbxpRY4MFB2xe6aEOjii4lC4i0/uO/i9ya7wVwoLWErdRLq1rPZH/feKYvhvPqJd8pTjk/nkBEVpPf0REE3YlrO9gNrdpklCIhCqv97fGQBNIVWeQhoqWdDSOQl63MWRPpumS0bZMtpPCzt+m28c1Y2wirYtUlbnHpHMEYPN/fJjlKMNl8fs+EiQT224HJFP49xnPO4tcvjgLx90yB6I+SiINCRtviHc1P7Gve1Et/qyI0JnRbbXYP4SXAThq6WjjEtG+EeLZl9n5s4HRs96EKiy3gvHcpd/q9dps94RYL638ETXiADhx5bpwm3QpQCj96bY1mJsMINhoXvqXFhlNfIICTOPYdf9AK5Fv1oW8wFRQk1GsS1daNKmMcHZwyGzGJ1YmtXFZ8iu2BJYyv+1N5OWEpuLRSRHFg3SdyRKIExLf39soyU5VfO6tRhPAI9kDoD4IoItASC3ahsZmUtqAj81NGnr0s8bLzGDms8kuYMZIPCeG8on5fj4IJZB7gJ8Y+2LvQU+QYeU75nxW2SKuH0qaEbZuydLkWG4qEgjxiMV2lMmOIpIG+OmE5LiZlieyTO4qS+Vdu0KrEMeWyBNWpDN5LZoT+BPSObbmr9WfSvE6Z/4x6+kQ=
